services:
  - type: web
    name: optivision-ai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
